### ISSUE TITLE
a single package.json at root

### ISSUE THREAD

**Issue by ttdonovan** [staratlasmeta/star-atlas-cookbook#2]
I just submitted a PR #1 that includes a few basic examples. I am wondering if the examples could just be individual ts scripts and a single `package.json` at the root for all examples (or even just within the `/examples/package.json`). Then the instructions would be as follows as example.

```
bun install
bun run examples/01-sage-game.ts
```

This would prevent the need to "init" each example and install redundant `node_modules` since each example will have overlapping share dependencies.

**Comment by mindrunner** [comment]
Makes sense to me! Feel free to refactor! :)
